services:
  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
      args:                                  
        BACKEND_PORT: ${BACKEND_PORT}
        SERVER_IP: ${SERVER_IP}
    env_file:
      - ./backend/fastapi/app/.env
    volumes:
      - ./backend/fastapi/app:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
     MARIADB_ROOT_PASSWORD: ${MARIA_PASSWORD} 
     MARIADB_DATABASE: finball
    volumes:
      - ./backend/mariadb/data:/var/lib/mysql
    ports:
      - "${MARIA_PORT}:${MARIA_PORT}"


  reactnative:
    build:
      context: ./frontend/react-native
      dockerfile: Dockerfile
      args:                                  
        FRONTEND_METRO_PORT: ${FRONTEND_METRO_PORT}
        FRONTEND_EXPO_PORT: ${FRONTEND_EXPO_PORT}
    env_file:
      - ./frontend/react-native/.env
    volumes:
      - ./frontend/react-native:/app
      - /app/node_modules 
      # node_modules만 빈 볼륨으로 오버라이드
    ports:
      - "${FRONTEND_METRO_PORT}:${FRONTEND_METRO_PORT}"
      - "${FRONTEND_EXPO_PORT}:${FRONTEND_EXPO_PORT}"

  nginx:
    image: nginx:latest
    depends_on:
    - fastapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
